INSERT INTO unit (id, name, description) VALUES (1, 'Unit 1', 'Description for Unit 1');
INSERT INTO unit (id, name, description) VALUES (2, 'Unit 2', 'Description for Unit 2');
INSERT INTO unit (id, name, description) VALUES (3, 'Unit 3', 'Description for Unit 3');
INSERT INTO unit (id, name, description) VALUES (4, 'Unit 4', 'Description for Unit 4');
INSERT INTO unit (id, name, description) VALUES (5, 'Unit 5', 'Description for Unit 5');
INSERT INTO unit (id, name, description) VALUES (6, 'Unit 6', 'Description for Unit 6');
INSERT INTO unit (id, name, description) VALUES (7, 'Unit 7', 'Description for Unit 7');
INSERT INTO unit (id, name, description) VALUES (8, 'Unit 8', 'Description for Unit 8');
INSERT INTO unit (id, name, description) VALUES (9, 'Unit 9', 'Description for Unit 9');
INSERT INTO unit (id, name, description) VALUES (10, 'Unit 10', 'Description for Unit 10');
INSERT INTO unit (id, name, description) VALUES (11, 'Unit 11', 'Description for Unit 11');
INSERT INTO unit (id, name, description) VALUES (12, 'Unit 12', 'Description for Unit 12');
INSERT INTO unit (id, name, description) VALUES (13, 'Unit 13', 'Description for Unit 13');
INSERT INTO unit (id, name, description) VALUES (14, 'Unit 14', 'Description for Unit 14');
INSERT INTO unit (id, name, description) VALUES (15, 'Unit 15', 'Description for Unit 15');
INSERT INTO unit (id, name, description) VALUES (16, 'Unit 16', 'Description for Unit 16');
INSERT INTO unit (id, name, description) VALUES (17, 'Unit 17', 'Description for Unit 17');
INSERT INTO unit (id, name, description) VALUES (18, 'Unit 18', 'Description for Unit 18');
INSERT INTO unit (id, name, description) VALUES (19, 'Unit 19', 'Description for Unit 19');
INSERT INTO unit (id, name, description) VALUES (20, 'Unit 20', 'Description for Unit 20');
INSERT INTO unit (id, name, description) VALUES (21, 'Unit 21', 'Description for Unit 21');
INSERT INTO unit (id, name, description) VALUES (22, 'Unit 22', 'Description for Unit 22');
INSERT INTO unit (id, name, description) VALUES (23, 'Unit 23', 'Description for Unit 23');
INSERT INTO unit (id, name, description) VALUES (24, 'Unit 24', 'Description for Unit 24');
INSERT INTO unit (id, name, description) VALUES (25, 'Unit 25', 'Description for Unit 25');
INSERT INTO unit (id, name, description) VALUES (26, 'Unit 26', 'Description for Unit 26');
INSERT INTO unit (id, name, description) VALUES (27, 'Unit 27', 'Description for Unit 27');
INSERT INTO unit (id, name, description) VALUES (28, 'Unit 28', 'Description for Unit 28');
INSERT INTO unit (id, name, description) VALUES (29, 'Unit 29', 'Description for Unit 29');
INSERT INTO unit (id, name, description) VALUES (30, 'Unit 30', 'Description for Unit 30');
INSERT INTO unit (id, name, description) VALUES (31, 'Unit 31', 'Description for Unit 31');
INSERT INTO unit (id, name, description) VALUES (32, 'Unit 32', 'Description for Unit 32');
INSERT INTO unit (id, name, description) VALUES (33, 'Unit 33', 'Description for Unit 33');
INSERT INTO unit (id, name, description) VALUES (34, 'Unit 34', 'Description for Unit 34');
INSERT INTO unit (id, name, description) VALUES (35, 'Unit 35', 'Description for Unit 35');
INSERT INTO unit (id, name, description) VALUES (36, 'Unit 36', 'Description for Unit 36');
INSERT INTO unit (id, name, description) VALUES (37, 'Unit 37', 'Description for Unit 37');
INSERT INTO unit (id, name, description) VALUES (38, 'Unit 38', 'Description for Unit 38');
INSERT INTO unit (id, name, description) VALUES (39, 'Unit 39', 'Description for Unit 39');
INSERT INTO unit (id, name, description) VALUES (40, 'Unit 40', 'Description for Unit 40');
INSERT INTO unit (id, name, description) VALUES (41, 'Unit 41', 'Description for Unit 41');
INSERT INTO unit (id, name, description) VALUES (42, 'Unit 42', 'Description for Unit 42');
INSERT INTO unit (id, name, description) VALUES (43, 'Unit 43', 'Description for Unit 43');
INSERT INTO unit (id, name, description) VALUES (44, 'Unit 44', 'Description for Unit 44');
INSERT INTO unit (id, name, description) VALUES (45, 'Unit 45', 'Description for Unit 45');
INSERT INTO unit (id, name, description) VALUES (46, 'Unit 46', 'Description for Unit 46');
INSERT INTO unit (id, name, description) VALUES (47, 'Unit 47', 'Description for Unit 47');
INSERT INTO unit (id, name, description) VALUES (48, 'Unit 48', 'Description for Unit 48');
INSERT INTO unit (id, name, description) VALUES (49, 'Unit 49', 'Description for Unit 49');
INSERT INTO unit (id, name, description) VALUES (50, 'Unit 50', 'Description for Unit 50');
INSERT INTO unit (id, name, description) VALUES (51, 'Unit 51', 'Description for Unit 51');
INSERT INTO unit (id, name, description) VALUES (52, 'Unit 52', 'Description for Unit 52');
INSERT INTO unit (id, name, description) VALUES (53, 'Unit 53', 'Description for Unit 53');
INSERT INTO unit (id, name, description) VALUES (54, 'Unit 54', 'Description for Unit 54');
INSERT INTO unit (id, name, description) VALUES (55, 'Unit 55', 'Description for Unit 55');
INSERT INTO unit (id, name, description) VALUES (56, 'Unit 56', 'Description for Unit 56');
INSERT INTO unit (id, name, description) VALUES (57, 'Unit 57', 'Description for Unit 57');
INSERT INTO unit (id, name, description) VALUES (58, 'Unit 58', 'Description for Unit 58');
INSERT INTO unit (id, name, description) VALUES (59, 'Unit 59', 'Description for Unit 59');
INSERT INTO unit (id, name, description) VALUES (60, 'Unit 60', 'Description for Unit 60');
INSERT INTO unit (id, name, description) VALUES (61, 'Unit 61', 'Description for Unit 61');
INSERT INTO unit (id, name, description) VALUES (62, 'Unit 62', 'Description for Unit 62');
INSERT INTO unit (id, name, description) VALUES (63, 'Unit 63', 'Description for Unit 63');
INSERT INTO unit (id, name, description) VALUES (64, 'Unit 64', 'Description for Unit 64');
INSERT INTO unit (id, name, description) VALUES (65, 'Unit 65', 'Description for Unit 65');
INSERT INTO unit (id, name, description) VALUES (66, 'Unit 66', 'Description for Unit 66');
INSERT INTO unit (id, name, description) VALUES (67, 'Unit 67', 'Description for Unit 67');
INSERT INTO unit (id, name, description) VALUES (68, 'Unit 68', 'Description for Unit 68');
INSERT INTO unit (id, name, description) VALUES (69, 'Unit 69', 'Description for Unit 69');
INSERT INTO unit (id, name, description) VALUES (70, 'Unit 70', 'Description for Unit 70');
INSERT INTO unit (id, name, description) VALUES (71, 'Unit 71', 'Description for Unit 71');
INSERT INTO unit (id, name, description) VALUES (72, 'Unit 72', 'Description for Unit 72');
INSERT INTO unit (id, name, description) VALUES (73, 'Unit 73', 'Description for Unit 73');
INSERT INTO unit (id, name, description) VALUES (74, 'Unit 74', 'Description for Unit 74');
INSERT INTO unit (id, name, description) VALUES (75, 'Unit 75', 'Description for Unit 75');
INSERT INTO unit (id, name, description) VALUES (76, 'Unit 76', 'Description for Unit 76');
INSERT INTO unit (id, name, description) VALUES (77, 'Unit 77', 'Description for Unit 77');

INSERT INTO config (id, app_key, app_value) VALUES (1, 'app.name', 'My Application');
INSERT INTO config (id, app_key, app_value) VALUES (2, 'app.version', '1.0.0');
INSERT INTO config (id, app_key, app_value) VALUES (3, 'app.environment', 'production');
INSERT INTO config (id, app_key, app_value) VALUES (4, 'db.url', 'jdbc:mysql://localhost:3306/mydb');
INSERT INTO config (id, app_key, app_value) VALUES (5, 'db.username', 'root');
INSERT INTO config (id, app_key, app_value) VALUES (6, 'db.password', 'password123');
INSERT INTO config (id, app_key, app_value) VALUES (7, 'cache.enabled', 'true');
INSERT INTO config (id, app_key, app_value) VALUES (8, 'cache.timeout', '300');
INSERT INTO config (id, app_key, app_value) VALUES (9, 'logging.level', 'DEBUG');
INSERT INTO config (id, app_key, app_value) VALUES (10, 'feature.newFeatureEnabled', 'false');

INSERT INTO book (id, title, author, category) VALUES (1, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction');
INSERT INTO book (id, title, author, category) VALUES (2, 'To Kill a Mockingbird', 'Harper Lee', 'Fiction');
INSERT INTO book (id, title, author, category) VALUES (3, '1984', 'George Orwell', 'Dystopian');
INSERT INTO book (id, title, author, category) VALUES (4, 'Pride and Prejudice', 'Jane Austen', 'Romance');
INSERT INTO book (id, title, author, category) VALUES (5, 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction');
INSERT INTO book (id, title, author, category) VALUES (6, 'Moby Dick', 'Herman Melville', 'Adventure');
INSERT INTO book (id, title, author, category) VALUES (7, 'War and Peace', 'Leo Tolstoy', 'Historical Fiction');
INSERT INTO book (id, title, author, category) VALUES (8, 'The Odyssey', 'Homer', 'Epic');
INSERT INTO book (id, title, author, category) VALUES (9, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy');
INSERT INTO book (id, title, author, category) VALUES (10, 'The Alchemist', 'Paulo Coelho', 'Fiction');
