version: '3'

services:
  mysql_db:
    image: mysql/mysql-server
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"